### ISSUE TITLE
Introducing and explaining content

### ISSUE THREAD

**Issue by Flighter13** [FieryChipmunk/FJs555-Website#1]
@FieryChipmunk 
_Tabs on website, links, et cetera_
### **Purposes of FJs 555**
- Discuss the purpose of fighter aircraft and their roles in air defense
- Analyze United States fighter aircraft and compare characteristics and specifications
- Discuss new air defense programs from the United States Air Force and others

### **Fighter Aircraft**

**American Aircraft**
- F-35 Lightning II -- _modern_
- F-22 Raptor -- _modern_
- F-18 Hornet -- _current_
- F-16 Falcon -- _current_
- F-15 Eagle -- _current_
- F-14 Tomcat -- _past_

**Non-American Aircraft**
- J-20
- Su-57
- FC-31
- Saab JAS 39
- Eurofighter Typhoon
- Dassault Rafale
- MiG-29
- Su-27

**Future Aircraft/Aircraft Prototypes**
- Next Generation Air Dominance (NGAD) fighter
- Su-75
- RQ-3 Darkstar (_though not a fighter aircraft_)

**Comment by Flighter13** [comment]
See https://github.com/Flighter13/Flighter13.github.io for the current setup of content on the website now (Flighter13.me), specifically _index.html_. Somehow, I shall move _home.html_ and the rest to the Flighter13.github.io to host the website @FieryChipmunk wrote/is writing.

**Comment by FieryChipmunk** [comment]
Ported all the text from the old website to this repo, issue closed, thanks.
